name: Manual Deploy

on: [push]

jobs:
  manual:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
    - name: Deploy manual
      run: echo "s" | python deploy_manual.py
